#!/usr/bin/env python3
import sys
import os

os.environ['CERBERO_UNINSTALLED']='1'
sys.path.insert(0, os.path.dirname(__file__))
sys.path.insert(1, os.path.join(os.path.dirname(__file__), "cerbero"))

os.environ['CERBERO_ROOT']= os.path.dirname(os.path.abspath(__file__))

from cerbero.main import main
sys.argv.insert(1, 'gtk-sharp-nuget.cbc')
sys.argv.insert(1, '-c')
main()